// AUTO-GENERATED from slidify/patterns/data/atoms.yaml.
// DO NOT EDIT — edit atoms.yaml + run `npm run codegen-atoms` instead.

// Re-exports for every codegen-emitted Tier-B recipe.
// Atelier-v2 (M7) imports from `@slidify/components/recipes/*` via this barrel.

export { default as AnnoBraceLabeled, annoBraceLabeledToIR, AnnoBraceLabeledVersion } from './AnnoBraceLabeled';
export type { AnnoBraceLabeledProps } from './AnnoBraceLabeled';
export { default as AnnoCalloutBubble, annoCalloutBubbleToIR, AnnoCalloutBubbleVersion } from './AnnoCalloutBubble';
export type { AnnoCalloutBubbleProps } from './AnnoCalloutBubble';
export { default as AnnoHighlighterMark, annoHighlighterMarkToIR, AnnoHighlighterMarkVersion } from './AnnoHighlighterMark';
export type { AnnoHighlighterMarkProps } from './AnnoHighlighterMark';
export { default as AnnoNumberedHotspot, annoNumberedHotspotToIR, AnnoNumberedHotspotVersion } from './AnnoNumberedHotspot';
export type { AnnoNumberedHotspotProps } from './AnnoNumberedHotspot';
export { default as AnnoRedactionBar, annoRedactionBarToIR, AnnoRedactionBarVersion } from './AnnoRedactionBar';
export type { AnnoRedactionBarProps } from './AnnoRedactionBar';
export { default as AnnoStampDraft, annoStampDraftToIR, AnnoStampDraftVersion } from './AnnoStampDraft';
export type { AnnoStampDraftProps } from './AnnoStampDraft';
export { default as AnnoStampInternal, annoStampInternalToIR, AnnoStampInternalVersion } from './AnnoStampInternal';
export type { AnnoStampInternalProps } from './AnnoStampInternal';
export { default as AnnoStampNew, annoStampNewToIR, AnnoStampNewVersion } from './AnnoStampNew';
export type { AnnoStampNewProps } from './AnnoStampNew';
export { default as AnnoSticker, annoStickerToIR, AnnoStickerVersion } from './AnnoSticker';
export type { AnnoStickerProps } from './AnnoSticker';
export { default as AnnoTooltip, annoTooltipToIR, AnnoTooltipVersion } from './AnnoTooltip';
export type { AnnoTooltipProps } from './AnnoTooltip';
export { default as BgAuroraCorners, bgAuroraCornersToIR, BgAuroraCornersVersion } from './BgAuroraCorners';
export type { BgAuroraCornersProps } from './BgAuroraCorners';
export { default as BgCrosshatch, bgCrosshatchToIR, BgCrosshatchVersion } from './BgCrosshatch';
export type { BgCrosshatchProps } from './BgCrosshatch';
export { default as BgDiagonal, bgDiagonalToIR, BgDiagonalVersion } from './BgDiagonal';
export type { BgDiagonalProps } from './BgDiagonal';
export { default as BgDotLatticeCoarse, bgDotLatticeCoarseToIR, BgDotLatticeCoarseVersion } from './BgDotLatticeCoarse';
export type { BgDotLatticeCoarseProps } from './BgDotLatticeCoarse';
export { default as BgDotLatticeFine, bgDotLatticeFineToIR, BgDotLatticeFineVersion } from './BgDotLatticeFine';
export type { BgDotLatticeFineProps } from './BgDotLatticeFine';
export { default as BgLineGrid, bgLineGridToIR, BgLineGridVersion } from './BgLineGrid';
export type { BgLineGridProps } from './BgLineGrid';
export { default as BgScrimBottom, bgScrimBottomToIR, BgScrimBottomVersion } from './BgScrimBottom';
export type { BgScrimBottomProps } from './BgScrimBottom';
export { default as BgScrimTop, bgScrimTopToIR, BgScrimTopVersion } from './BgScrimTop';
export type { BgScrimTopProps } from './BgScrimTop';
export { default as BgSpotlightSoft, bgSpotlightSoftToIR, BgSpotlightSoftVersion } from './BgSpotlightSoft';
export type { BgSpotlightSoftProps } from './BgSpotlightSoft';
export { default as BgSpotlightTight, bgSpotlightTightToIR, BgSpotlightTightVersion } from './BgSpotlightTight';
export type { BgSpotlightTightProps } from './BgSpotlightTight';
export { default as CompAgenda2col, compAgenda2colToIR, CompAgenda2colVersion } from './CompAgenda2col';
export type { CompAgenda2colProps } from './CompAgenda2col';
export { default as CompAgendaToc, compAgendaTocToIR, CompAgendaTocVersion } from './CompAgendaToc';
export type { CompAgendaTocProps } from './CompAgendaToc';
export { default as CompAnnotatedScreenshot, compAnnotatedScreenshotToIR, CompAnnotatedScreenshotVersion } from './CompAnnotatedScreenshot';
export type { CompAnnotatedScreenshotProps } from './CompAnnotatedScreenshot';
export { default as CompBentoMixed, compBentoMixedToIR, CompBentoMixedVersion } from './CompBentoMixed';
export type { CompBentoMixedProps } from './CompBentoMixed';
export { default as CompBigStatHero, compBigStatHeroToIR, CompBigStatHeroVersion } from './CompBigStatHero';
export type { CompBigStatHeroProps } from './CompBigStatHero';
export { default as CompClosingCta, compClosingCtaToIR, CompClosingCtaVersion } from './CompClosingCta';
export type { CompClosingCtaProps } from './CompClosingCta';
export { default as CompDataOverview, compDataOverviewToIR, CompDataOverviewVersion } from './CompDataOverview';
export type { CompDataOverviewProps } from './CompDataOverview';
export { default as CompHeroInvestor, compHeroInvestorToIR, CompHeroInvestorVersion } from './CompHeroInvestor';
export type { CompHeroInvestorProps } from './CompHeroInvestor';
export { default as CompHeroProduct, compHeroProductToIR, CompHeroProductVersion } from './CompHeroProduct';
export type { CompHeroProductProps } from './CompHeroProduct';
export { default as CompQuoteEditorial, compQuoteEditorialToIR, CompQuoteEditorialVersion } from './CompQuoteEditorial';
export type { CompQuoteEditorialProps } from './CompQuoteEditorial';
export { default as CompRoadmapQuarterly, compRoadmapQuarterlyToIR, CompRoadmapQuarterlyVersion } from './CompRoadmapQuarterly';
export type { CompRoadmapQuarterlyProps } from './CompRoadmapQuarterly';
export { default as CompSectionDividerMesh, compSectionDividerMeshToIR, CompSectionDividerMeshVersion } from './CompSectionDividerMesh';
export type { CompSectionDividerMeshProps } from './CompSectionDividerMesh';
export { default as CompTeamGrid, compTeamGridToIR, CompTeamGridVersion } from './CompTeamGrid';
export type { CompTeamGridProps } from './CompTeamGrid';
export { default as CompThreeUpStats, compThreeUpStatsToIR, CompThreeUpStatsVersion } from './CompThreeUpStats';
export type { CompThreeUpStatsProps } from './CompThreeUpStats';
export { default as DataBarSetH, dataBarSetHToIR, DataBarSetHVersion } from './DataBarSetH';
export type { DataBarSetHProps } from './DataBarSetH';
export { default as DataBarSetV, dataBarSetVToIR, DataBarSetVVersion } from './DataBarSetV';
export type { DataBarSetVProps } from './DataBarSetV';
export { default as DataBulletBar, dataBulletBarToIR, DataBulletBarVersion } from './DataBulletBar';
export type { DataBulletBarProps } from './DataBulletBar';
export { default as DataConnector, dataConnectorToIR, DataConnectorVersion } from './DataConnector';
export type { DataConnectorProps } from './DataConnector';
export { default as DataDataTable, dataDataTableToIR, DataDataTableVersion } from './DataDataTable';
export type { DataDataTableProps } from './DataDataTable';
export { default as DataDeltaBadge, dataDeltaBadgeToIR, DataDeltaBadgeVersion } from './DataDeltaBadge';
export type { DataDeltaBadgeProps } from './DataDeltaBadge';
export { default as DataDonut, dataDonutToIR, DataDonutVersion } from './DataDonut';
export type { DataDonutProps } from './DataDonut';
export { default as DataDonutMultiSegment, dataDonutMultiSegmentToIR, DataDonutMultiSegmentVersion } from './DataDonutMultiSegment';
export type { DataDonutMultiSegmentProps } from './DataDonutMultiSegment';
export { default as DataKpiRow, dataKpiRowToIR, DataKpiRowVersion } from './DataKpiRow';
export type { DataKpiRowProps } from './DataKpiRow';
export { default as DataMiniHeatmap, dataMiniHeatmapToIR, DataMiniHeatmapVersion } from './DataMiniHeatmap';
export type { DataMiniHeatmapProps } from './DataMiniHeatmap';
export { default as DecArrowDown, decArrowDownToIR, DecArrowDownVersion } from './DecArrowDown';
export type { DecArrowDownProps } from './DecArrowDown';
export { default as DecArrowLeft, decArrowLeftToIR, DecArrowLeftVersion } from './DecArrowLeft';
export type { DecArrowLeftProps } from './DecArrowLeft';
export { default as DecArrowRight, decArrowRightToIR, DecArrowRightVersion } from './DecArrowRight';
export type { DecArrowRightProps } from './DecArrowRight';
export { default as DecArrowUp, decArrowUpToIR, DecArrowUpVersion } from './DecArrowUp';
export type { DecArrowUpProps } from './DecArrowUp';
export { default as DecBraceBottom, decBraceBottomToIR, DecBraceBottomVersion } from './DecBraceBottom';
export type { DecBraceBottomProps } from './DecBraceBottom';
export { default as DecBraceLeft, decBraceLeftToIR, DecBraceLeftVersion } from './DecBraceLeft';
export type { DecBraceLeftProps } from './DecBraceLeft';
export { default as DecBraceRight, decBraceRightToIR, DecBraceRightVersion } from './DecBraceRight';
export type { DecBraceRightProps } from './DecBraceRight';
export { default as DecBraceTop, decBraceTopToIR, DecBraceTopVersion } from './DecBraceTop';
export type { DecBraceTopProps } from './DecBraceTop';
export { default as DecBulletDot, decBulletDotToIR, DecBulletDotVersion } from './DecBulletDot';
export type { DecBulletDotProps } from './DecBulletDot';
export { default as DecCornerCrop, decCornerCropToIR, DecCornerCropVersion } from './DecCornerCrop';
export type { DecCornerCropProps } from './DecCornerCrop';
export { default as DecDottedRule, decDottedRuleToIR, DecDottedRuleVersion } from './DecDottedRule';
export type { DecDottedRuleProps } from './DecDottedRule';
export { default as DecHairlineRule, decHairlineRuleToIR, DecHairlineRuleVersion } from './DecHairlineRule';
export type { DecHairlineRuleProps } from './DecHairlineRule';
export { default as DecNumeralChapter, decNumeralChapterToIR, DecNumeralChapterVersion } from './DecNumeralChapter';
export type { DecNumeralChapterProps } from './DecNumeralChapter';
export { default as DecPlus, decPlusToIR, DecPlusVersion } from './DecPlus';
export type { DecPlusProps } from './DecPlus';
export { default as DecSectionDivider, decSectionDividerToIR, DecSectionDividerVersion } from './DecSectionDivider';
export type { DecSectionDividerProps } from './DecSectionDivider';
export { default as DecStar5, decStar5ToIR, DecStar5Version } from './DecStar5';
export type { DecStar5Props } from './DecStar5';
export { default as DecStar6, decStar6ToIR, DecStar6Version } from './DecStar6';
export type { DecStar6Props } from './DecStar6';
export { default as MaskCallout, maskCalloutToIR, MaskCalloutVersion } from './MaskCallout';
export type { MaskCalloutProps } from './MaskCallout';
export { default as MaskGradientFadeEdge, maskGradientFadeEdgeToIR, MaskGradientFadeEdgeVersion } from './MaskGradientFadeEdge';
export type { MaskGradientFadeEdgeProps } from './MaskGradientFadeEdge';
export { default as MaskOctagon, maskOctagonToIR, MaskOctagonVersion } from './MaskOctagon';
export type { MaskOctagonProps } from './MaskOctagon';
export { default as MaskRoundedRectClip, maskRoundedRectClipToIR, MaskRoundedRectClipVersion } from './MaskRoundedRectClip';
export type { MaskRoundedRectClipProps } from './MaskRoundedRectClip';
export { default as SurfBentoCell, surfBentoCellToIR, SurfBentoCellVersion } from './SurfBentoCell';
export type { SurfBentoCellProps } from './SurfBentoCell';
export { default as SurfCardBordered, surfCardBorderedToIR, SurfCardBorderedVersion } from './SurfCardBordered';
export type { SurfCardBorderedProps } from './SurfCardBordered';
export { default as SurfCardDepth, surfCardDepthToIR, SurfCardDepthVersion } from './SurfCardDepth';
export type { SurfCardDepthProps } from './SurfCardDepth';
export { default as SurfCardFlat, surfCardFlatToIR, SurfCardFlatVersion } from './SurfCardFlat';
export type { SurfCardFlatProps } from './SurfCardFlat';
export { default as SurfCardFloating, surfCardFloatingToIR, SurfCardFloatingVersion } from './SurfCardFloating';
export type { SurfCardFloatingProps } from './SurfCardFloating';
export { default as SurfCardPaper, surfCardPaperToIR, SurfCardPaperVersion } from './SurfCardPaper';
export type { SurfCardPaperProps } from './SurfCardPaper';
export { default as SurfCardRaised, surfCardRaisedToIR, SurfCardRaisedVersion } from './SurfCardRaised';
export type { SurfCardRaisedProps } from './SurfCardRaised';
export { default as SurfFrameLetterbox, surfFrameLetterboxToIR, SurfFrameLetterboxVersion } from './SurfFrameLetterbox';
export type { SurfFrameLetterboxProps } from './SurfFrameLetterbox';
export { default as SurfSectionBand, surfSectionBandToIR, SurfSectionBandVersion } from './SurfSectionBand';
export type { SurfSectionBandProps } from './SurfSectionBand';
export { default as SurfTapeBand, surfTapeBandToIR, SurfTapeBandVersion } from './SurfTapeBand';
export type { SurfTapeBandProps } from './SurfTapeBand';
export { default as TypeBigNumber, typeBigNumberToIR, TypeBigNumberVersion } from './TypeBigNumber';
export type { TypeBigNumberProps } from './TypeBigNumber';
export { default as TypeBigNumberGradient, typeBigNumberGradientToIR, TypeBigNumberGradientVersion } from './TypeBigNumberGradient';
export type { TypeBigNumberGradientProps } from './TypeBigNumberGradient';
export { default as TypeBigNumberXl, typeBigNumberXlToIR, TypeBigNumberXlVersion } from './TypeBigNumberXl';
export type { TypeBigNumberXlProps } from './TypeBigNumberXl';
export { default as TypeEyebrowRuled, typeEyebrowRuledToIR, TypeEyebrowRuledVersion } from './TypeEyebrowRuled';
export type { TypeEyebrowRuledProps } from './TypeEyebrowRuled';
export { default as TypeEyebrowTape, typeEyebrowTapeToIR, TypeEyebrowTapeVersion } from './TypeEyebrowTape';
export type { TypeEyebrowTapeProps } from './TypeEyebrowTape';
export { default as TypeNumeralsTabular, typeNumeralsTabularToIR, TypeNumeralsTabularVersion } from './TypeNumeralsTabular';
export type { TypeNumeralsTabularProps } from './TypeNumeralsTabular';
export { default as TypePullquoteBrutalist, typePullquoteBrutalistToIR, TypePullquoteBrutalistVersion } from './TypePullquoteBrutalist';
export type { TypePullquoteBrutalistProps } from './TypePullquoteBrutalist';
export { default as TypePullquoteSerif, typePullquoteSerifToIR, TypePullquoteSerifVersion } from './TypePullquoteSerif';
export type { TypePullquoteSerifProps } from './TypePullquoteSerif';
export { default as UiBrowserMac, uiBrowserMacToIR, UiBrowserMacVersion } from './UiBrowserMac';
export type { UiBrowserMacProps } from './UiBrowserMac';
export { default as UiBrowserMinimal, uiBrowserMinimalToIR, UiBrowserMinimalVersion } from './UiBrowserMinimal';
export type { UiBrowserMinimalProps } from './UiBrowserMinimal';
export { default as UiBrowserWin, uiBrowserWinToIR, UiBrowserWinVersion } from './UiBrowserWin';
export type { UiBrowserWinProps } from './UiBrowserWin';
export { default as UiChecklist, uiChecklistToIR, UiChecklistVersion } from './UiChecklist';
export type { UiChecklistProps } from './UiChecklist';
export { default as UiCodeBlock, uiCodeBlockToIR, UiCodeBlockVersion } from './UiCodeBlock';
export type { UiCodeBlockProps } from './UiCodeBlock';
export { default as UiCodeBlockSyntax, uiCodeBlockSyntaxToIR, UiCodeBlockSyntaxVersion } from './UiCodeBlockSyntax';
export type { UiCodeBlockSyntaxProps } from './UiCodeBlockSyntax';
export { default as UiDeviceLaptop, uiDeviceLaptopToIR, UiDeviceLaptopVersion } from './UiDeviceLaptop';
export type { UiDeviceLaptopProps } from './UiDeviceLaptop';
export { default as UiDevicePhone, uiDevicePhoneToIR, UiDevicePhoneVersion } from './UiDevicePhone';
export type { UiDevicePhoneProps } from './UiDevicePhone';
export { default as UiProgressBar, uiProgressBarToIR, UiProgressBarVersion } from './UiProgressBar';
export type { UiProgressBarProps } from './UiProgressBar';
export { default as UiStatusDot, uiStatusDotToIR, UiStatusDotVersion } from './UiStatusDot';
export type { UiStatusDotProps } from './UiStatusDot';
export { default as UiStepper, uiStepperToIR, UiStepperVersion } from './UiStepper';
export type { UiStepperProps } from './UiStepper';
export { default as UiTerminalWindow, uiTerminalWindowToIR, UiTerminalWindowVersion } from './UiTerminalWindow';
export type { UiTerminalWindowProps } from './UiTerminalWindow';
